[general]
live_config_reload = true
import = ["./themes/moonfly.toml"]

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations_theme_variant = "Dark"
resize_increments = true

[font]
# MesloLGS Nerd Font Mono, BlexMono Nerd Font Mono
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
offset = { y = 4 }
size = 14

[selection]
save_to_clipboard = true

[terminal]
shell = "/bin/zsh"
