# Specify a directory to install casks

cask_args appdir: '/Applications'

# Install packages

brew 'zsh'
brew 'zsh-syntax-highlighting'
brew 'zsh-autosuggestions'
brew 'bat'
brew 'fortune'
brew 'cowsay'
brew 'fzf'
brew 'neovim'
brew 'lazygit'
brew 'stow'
brew 'ripgrep'
brew 'oh-my-posh'

cask 'raycast'
cask 'arc'
cask 'font-fira-code-nerd-font'
cask 'font-jetbrains-mono-nerd-font'
cask 'visual-studio-code'
cask 'zed'
cask 'nikitabobko/tap/aerospace'
