format = '$directory$character'
right_format = '$git_branch$git_status'

add_newline = false

[directory]
fish_style_pwd_dir_length = 1
style = 'bold #737aa2'

[git_branch]
format = 'on [$symbol$branch]($style) '
style = 'bold #7aa2f7'
symbol = ' '

