format = '$directory$git_branch$git_status[\$](bold) '

add_newline = false

[directory]
fish_style_pwd_dir_length = 1
style = 'bold #737aa2'

[git_branch]
format = 'on [$symbol$branch]($style) '
style = 'bold #7aa2f7'
symbol = ' '

[git_status]
format = '([$modified]($style) )'
style = "bold #ff757f"
modified = "✘"
