version = 3

[[blocks]]
type = 'prompt'
alignment = 'left'

[[blocks.segments]]
style = "plain"
template = "{{ if .Error }}<#E06C75>{{else}}<#98C379>{{end}}➜</> "
type = "status"
properties.always_enabled = true

[[blocks.segments]]
template = '{{ .Path }} '
foreground = 'cyan'
type = 'path'
style = 'plain'

[blocks.segments.properties]
style = 'folder'

[[blocks.segments]]
type = "git"
foreground = "#D0666F"
style = "plain"
template = "<#5FAAE8>git:(</>{{ .HEAD }}<#5FAAE8>)</> "

[blocks.segments.properties]
branch_icon = ""

[[blocks.segments]]
template = '{{ if .Working.Changed }}✗ {{ end }}'
foreground = 'yellow'
type = 'git'
style = 'plain'
properties.fetch_status = true
