[general]
live_config_reload = true

[window]
padding = { x = 5, y = 5 }
dynamic_padding = true
decorations_theme_variant = "Dark"
resize_increments = true
# opacity = 0.75
# blur = true

[font]
normal = { family = "BlexMono Nerd Font Mono", style = "Regular"}
size = 14
offset = { y = 2 }

[selection]
save_to_clipboard = true

[terminal]
shell = "/bin/zsh"

